# Site settings
title: 晨美環保科技
email: info@jycmkj.com
keywords: "煤气抽水车,环卫车辆,环卫清扫车,环卫垃圾车,环卫电动车,环卫工作,环卫汽车检测场,环卫车改装"
description: "江陰市晨美環保科技有限公司是一家集"
baseurl: ""
url: "http://www.jycmkj.com"

# Build settings
markdown: kramdown
permalink: pretty

timezone: Asia/Shanghai