# Site settings
title: 晨美環保科技有限公司
email: info@jycmkj.com
keywords: "电动清扫车、电动冲洗车、电动清运车、电动保洁车、电动巡逻车、观光车及电动民用车辆"
description: "江阴市晨美环保科技有限公司是集一家电动环卫车的研发、生产、销售、以及城市公共环境管理的、道路清扫保洁、垃圾收运服务于一体的现代化低碳型企业。公司生产的电动车拥有多项国家专利，通过了国家工程机械质量检测中心检测、特种设备形式实验合格证、并获得了国家质检总局颁发的特种设备制造许可证，通过了ISO9001质量管理体系认证和ISO14001环境体系认证，是中国环境卫生协会、北京环境卫生协会、上海环境卫生设备委员会、杭州市城镇环境卫生协会会员单位。"
baseurl: ""
url: "http://www.jycmkj.com"

# Build settings
markdown: kramdown
permalink: pretty

timezone: Asia/Shanghai